[package]
name = "cowsay"
version = "1.0.0"
authors = ["Sayan Nandan <nandansayan@outlook.com>"]
edition = "2018"
description = "The old cowsay, written in new Rust"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
